### ISSUE TITLE
arro ao rodar o script 2_... .sql

### ISSUE THREAD

**Issue by wll8090** [anatelgovbr/sei-em-numeros#7]
ERROR 1452 (23000) at line 11: Cannot add or update a child row: a foreign key constraint fails (`sei`.`assunto`, CONSTRAINT `fk_assunto_tabela_assuntos` FOREIGN KEY (`id_tabela_assuntos`) REFERENCES `tabela_assuntos` (`id_tabela_assuntos`))

**Comment by neijobson** [comment]
Problema local.
Releia o README.
É de cada órgão entender o script e ajustar para suas necessidades. Não damos suporte no script e em questões locais.
